# Generated by Django 3.2.9 on 2021-12-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20211215_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(max_length=254, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='announcementimage',
            name='image',
            field=models.ImageField(max_length=254, upload_to='images'),
        ),
    ]
